# Generated by Django 6.0.5 on 2026-05-13 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('seniority', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], default='senior', max_length=100)),
                ('main_skills', models.JSONField(default=list)),
                ('secondary_skills', models.JSONField(default=list)),
                ('industries', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('preferred_locations', models.JSONField(default=list)),
                ('remote_preference', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='hybrid', max_length=20)),
                ('target_salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('target_salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
