# Generated by Django 6.0.5 on 2026-05-13 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('raw_description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('remote_policy', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True)),
                ('required_skills', models.JSONField(default=list)),
                ('nice_to_have_skills', models.JSONField(default=list)),
                ('extracted_skills', models.JSONField(default=list)),
                ('seniority', models.CharField(blank=True, max_length=100, null=True)),
                ('business_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('red_flag', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('generated_pitch', models.TextField(blank=True, null=True)),
                ('generated_cover_letter', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.joboffer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
