# Generated by Django 6.0.5 on 2026-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='source',
            field=models.CharField(choices=[('LinkedIn', 'Linkedin'), ('HelloWork', 'Hellowork'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
