"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# python-dotenv is used to load environment variables from a .env file in development
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+*zar4eb%w+-22a_!*$k%zqc6is^25+h*+gp_6om5)@-flka4n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

INSTALLED_APPS += [
    'apps.accounts',
    'apps.ai',
    'apps.applications',
    'apps.core',
    'apps.jobs',
    'apps.profiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS settings
CORS_ALLOW_ALL_ORIGINS = False
CORS_ORIGIN_WHITELIST = [
    'http://localhost:4200',
    'http://127.0.0.1:4200',
    'https://delitamakanda.github.io',
]
CORS_ALLOW_CREDENTIALS = True

# Rest Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Primary: token read from an httpOnly cookie (browser SPA).
        'apps.accounts.authentication.CookieTokenAuthentication',
        # Fallback: token in the Authorization header (non-browser/API clients).
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# --- Cookie-based auth token + CSRF ---------------------------------------
def _env_bool(name, default):
    return os.getenv(name, str(default)).lower() in ('1', 'true', 'yes', 'on')


# In production the SPA (e.g. https://delitamakanda.github.io) and this API
# (e.g. https://api.careeragent.dev) are served from different sites, so the
# auth/CSRF cookies must be `SameSite=None; Secure`. In local development
# (same host over http) `SameSite=Lax` without Secure is used instead.
# Set CROSS_SITE_COOKIES=1 (and serve the API over HTTPS) in production.
CROSS_SITE_COOKIES = _env_bool('CROSS_SITE_COOKIES', not DEBUG)

# httpOnly cookie that carries the DRF auth token.
AUTH_COOKIE_NAME = os.getenv('AUTH_COOKIE_NAME', 'auth_token')
AUTH_COOKIE_MAX_AGE = int(os.getenv('AUTH_COOKIE_MAX_AGE', 60 * 60 * 24 * 14))  # 14 days
AUTH_COOKIE_DOMAIN = os.getenv('AUTH_COOKIE_DOMAIN') or None
AUTH_COOKIE_PATH = '/'
AUTH_COOKIE_SAMESITE = 'None' if CROSS_SITE_COOKIES else 'Lax'
AUTH_COOKIE_SECURE = _env_bool('AUTH_COOKIE_SECURE', CROSS_SITE_COOKIES)

# CSRF double-submit. The token is handed to the SPA in the body of
# /api/auth/csrf/ (a cross-domain SPA cannot read the API's cookie), echoed
# back in the X-CSRFToken header, and validated against the csrftoken cookie
# the browser sends automatically. The cookie must be JS-visible.
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'None' if CROSS_SITE_COOKIES else 'Lax'
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', CROSS_SITE_COOKIES)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:4200',
    'http://127.0.0.1:4200',
    'https://delitamakanda.github.io',
]

# AI settings
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', 'your_openai_api_key')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-5.4-mini')